export const foodMenu = [
    {
        category: { label: 'Салаты', iconSrc: '/icons/eggplant.png', slug: 'salads' },
        subcategories: [
            { label: 'Мясные салаты', slug: '' },
            { label: 'Рыбные салаты', slug: '' },
            { label: 'Овощные салаты', slug: '' },
            { label: 'Теплые салаты', slug: '' },
        ],
    },
    {
        category: { label: 'Закуски', iconSrc: '/icons/healthy-eating.png', slug: 'snacks' },
        subcategories: [
            { label: 'Мясные закуски', slug: '' },
            { label: 'Рыбные закуски', slug: '' },
            { label: 'Овощные закуски', slug: '' },
            { label: 'Теплые закуски', slug: '' },
            { label: 'Бутерброды', slug: '' },
            { label: 'Фастфуд', slug: '' },
        ],
    },
    {
        category: { label: 'Первые блюда', iconSrc: '/icons/pot.png', slug: 'first-courses' },
        subcategories: [
            { label: 'Мясные супы', slug: '' },
            { label: 'Овощные супы', slug: '' },
            { label: 'Бульоны', slug: '' },
            { label: 'Холодные супы', slug: '' },
            { label: 'Диетические супы', slug: '' },
        ],
    },
    {
        category: {
            label: 'Вторые блюда',
            iconSrc: '/icons/frying-pan.png',
            slug: 'second-courses',
        },
        subcategories: [
            { label: 'Мясные', slug: '' },
            { label: 'Рыбные', slug: '' },
            { label: 'Овощные', slug: '' },
            { label: 'Из птицы', slug: '' },
            { label: 'Из грибов', slug: '' },
            { label: 'Из субпродуктов', slug: '' },
            { label: 'На пару', slug: '' },
            { label: 'Пельмени, вареники', slug: '' },
            { label: 'Мучные гарниры', slug: '' },
            { label: 'Овощные гарниры', slug: '' },
            { label: 'Пицца', slug: '' },
            { label: 'Суши', slug: '' },
        ],
    },
    {
        category: {
            label: 'Десерты, выпечка',
            iconSrc: '/icons/rolling-pin.png',
            slug: 'desserts-pastry',
        },
        subcategories: [
            { label: 'Блины и оладьи', slug: '' },
            { label: 'Пироги и пончики', slug: '' },
            { label: 'Торты', slug: '' },
            { label: 'Рулеты', slug: '' },
            { label: 'Кексы и маффины', slug: '' },
            { label: 'Сырники и ватрушки', slug: '' },
            { label: 'Из слоеного теста', slug: '' },
            { label: 'Из заварного теста', slug: '' },
            { label: 'Из дрожжевого теста', slug: '' },
            { label: 'Булочки и сдоба', slug: '' },
            { label: 'Хлеб', slug: '' },
            { label: 'Тесто на пиццу', slug: '' },
            { label: 'Кремы', slug: '' },
        ],
    },
    {
        category: { label: 'Блюда на гриле', iconSrc: '/icons/grill.png', slug: 'grill' },
        subcategories: [
            { label: 'Говядина', slug: '' },
            { label: 'Свинина', slug: '' },
            { label: 'Птица', slug: '' },
            { label: 'Рыба', slug: '' },
            { label: 'Грибы', slug: '' },
            { label: 'Овощи', slug: '' },
        ],
    },
    {
        category: { label: 'Веганская кухня', iconSrc: '/icons/bay-leaf.png', slug: 'vegan' },
        subcategories: [
            { label: 'Закуски', slug: '' },
            { label: 'Первые блюда', slug: '' },
            { label: 'Вторые блюда', slug: 'second-courses' },
            { label: 'Гарниры', slug: '' },
            { label: 'Десерты', slug: '' },
            { label: 'Выпечка', slug: '' },
            { label: 'Сыроедческие блюда', slug: '' },
            { label: 'Напитки', slug: '' },
        ],
    },
    {
        category: { label: 'Детские блюда', iconSrc: '/icons/child-tasty.png', slug: 'children' },
        subcategories: [
            { label: 'Первые блюда', slug: '' },
            { label: 'Вторые блюда', slug: '' },
            { label: 'Гарниры', slug: '' },
            { label: 'Выпечка', slug: '' },
            { label: 'Без глютена', slug: '' },
            { label: 'Без сахара', slug: '' },
            { label: 'Без аллергенов', slug: '' },
            { label: 'Блюда для прикорма', slug: '' },
        ],
    },
    {
        category: {
            label: 'Лечебное питание',
            iconSrc: '/icons/pot-with-cross.svg',
            slug: 'healthy',
        },
        subcategories: [
            { label: 'Детская диета', slug: '' },
            { label: 'Диета №1', slug: '' },
            { label: 'Диета №2', slug: '' },
            { label: 'Диета №3', slug: '' },
            { label: 'Диета №4', slug: '' },
            { label: 'Диета №5', slug: '' },
            { label: 'Диета №6', slug: '' },
            { label: 'Диета №7', slug: '' },
            { label: 'Диета №8', slug: '' },
            { label: 'Диета №9', slug: '' },
            { label: 'Диета №10', slug: '' },
            { label: 'Диета №11', slug: '' },
            { label: 'Диета №12', slug: '' },
            { label: 'Диета №13', slug: '' },
            { label: 'Диета №14', slug: '' },
            { label: 'Без глютена', slug: '' },
            { label: 'Без аллергенов', slug: '' },
        ],
    },
    {
        category: {
            label: 'Национальные',
            iconSrc: '/icons/international-food.png',
            slug: 'international',
        },
        subcategories: [
            { label: 'Американская кухня', slug: '' },
            { label: 'Армянская кухня', slug: '' },
            { label: 'Греческая кухня', slug: '' },
            { label: 'Грузинская кухня', slug: '' },
            { label: 'Итальянская кухня', slug: '' },
            { label: 'Испанская кухня', slug: '' },
            { label: 'Китайская кухня', slug: '' },
            { label: 'Мексиканская кухня', slug: '' },
            { label: 'Паназиатская кухня', slug: '' },
            { label: 'Русская кухня', slug: '' },
            { label: 'Турецкая кухня', slug: '' },
            { label: 'Французская кухня', slug: '' },
            { label: 'Шведская кухня', slug: '' },
            { label: 'Японская кухня', slug: '' },
            { label: 'Другая кухня', slug: '' },
        ],
    },
    {
        category: { label: 'Соусы', iconSrc: '/icons/mortar.png', slug: 'sauces' },
        subcategories: [
            { label: 'Соусы мясные', slug: '' },
            { label: 'Соусы сырные', slug: '' },
            { label: 'Маринады', slug: '' },
        ],
    },
    {
        category: { label: 'Напитки', iconSrc: '/icons/cup.png', slug: 'beverages' },
        subcategories: [
            { label: 'Соки и фреши', slug: '' },
            { label: 'Смузи', slug: '' },
            { label: 'Компоты', slug: '' },
            { label: 'Кисели', slug: '' },
            { label: 'Кофе', slug: '' },
            { label: 'Лечебный чай', slug: '' },
            { label: 'Квас', slug: '' },
            { label: 'Коктейли', slug: '' },
            { label: 'Алкогольные', slug: '' },
        ],
    },
    {
        category: { label: 'Заготовки', iconSrc: '/icons/carrot-jar.png', slug: 'ready-made' },
        subcategories: [
            { label: 'Мясные заготовки', slug: '' },
            { label: 'Рыбные заготовки', slug: '' },
            { label: 'Из огурцов', slug: '' },
            { label: 'Из томатов', slug: '' },
            { label: 'Из грибов', slug: '' },
            { label: 'Овощные заготовки', slug: '' },
            { label: 'Салаты, икра', slug: '' },
            { label: 'Из фруктов и ягод', slug: '' },
        ],
    },
];
