export const TestId = {
    APP_LOADER: 'app-loader',
    ERROR_ALERT: 'error-notification',
    ERROR_ALERT_CLOSE: 'close-alert-button',
    LOAD_MORE_BUTTON: 'load-more-button',
    SEARCH_BAR_LOADER: 'loader-search-block',
    PAGE_NOT_FOUND_LINK: 'error-page-go-home',
    RECIPE_MENU_VEGAN: 'vegan-cuisine',
    JUICIEST_LINK: 'juiciest-link',
    JUICIEST_LINK_MOBILE: 'juiciest-link-mobile',
    ALLERGEN_SWITCH: 'allergens-switcher',
    ALLERGEN_SWITCH_DRAWER: 'allergens-switcher-filter',
    ALLERGEN_SELECT_DRAWER: 'allergens-menu-button-filter',
    ALLERGEN_SELECT: 'allergens-menu-button',
    ALLERGEN_SELECT_MENU: 'allergens-menu',
    ALLERGEN_ADD_OTHER_INPUT: 'add-other-allergen',
    ALLERGEN_ADD_OTHER_BUTTON: 'add-allergen-button',
    CATEGORY_SELECT: 'filter-menu-button-категория',
    VEGAN_CATEGORY_SELECT_OPTION: 'checkbox-веганская кухня',
    POTATO_GARNISH_OPTION: 'checkbox-картошка',
    FIND_RECIPE_BUTTON: 'find-recipe-button',
    CLEAR_FILTERS_BUTTON: 'clear-filter-button',
    allergenSelectOption: (idx: number) => `allergen-${idx}`,
    recipeCard: (idx: number) => `food-card-${idx}`,
    recipeCardLink: (idx: number) => `card-link-${idx}`,
};
