export const recipeCategoryMap: Record<
    string,
    { label: string; iconSrc: string; subcategories: Record<string, { label: string }> }
> = {
    salads: {
        label: 'Салаты',
        iconSrc: '/icons/eggplant.png',
        subcategories: {
            meat: { label: 'Мясные салаты' },
            fish: { label: 'Рыбные салаты' },
            vegetables: { label: 'Овощные салаты' },
            'warm-salads': { label: 'Теплые салаты' },
        },
    },
    snacks: {
        label: 'Закуски',
        iconSrc: '/icons/healthy-eating.png',
        subcategories: {
            meat: { label: 'Мясные закуски' },
            fish: { label: 'Рыбные закуски' },
            vegetables: { label: 'Овощные закуски' },
            'warm-snacks': { label: 'Теплые закуски' },
            sandwiches: { label: 'Бутерброды' },
            fastfood: { label: 'Фастфуд' },
        },
    },
    'first-dish': {
        label: 'Первые блюда',
        iconSrc: '/icons/pot.png',
        subcategories: {
            fish: { label: 'Мясные супы' },
            vegetables: { label: 'Овощные супы' },
            broths: { label: 'Бульоны' },
            cold: { label: 'Холодные супы' },
            diet: { label: 'Диетические супы' },
        },
    },
    'second-dish': {
        label: 'Вторые блюда',
        iconSrc: '/icons/frying-pan.png',
        subcategories: {
            meat: { label: 'Мясные' },
            fish: { label: 'Рыбные' },
            vegetables: { label: 'Овощные' },
            'poultry-dish': { label: 'Из птицы' },
            'mushroom-dish': { label: 'Из грибов' },
            'byproduct-dish': { label: 'Из субпродуктов' },
            'steamed-dish': { label: 'На пару' },
            pierogi: { label: 'Пельмени, вареники' },
            'flour-garnish': { label: 'Мучные гарниры' },
            'vegetebles-garnish': { label: 'Овощные гарниры' },
            pizza: { label: 'Пицца' },
            sushi: { label: 'Суши' },
        },
    },
    'desserts-pastry': {
        label: 'Десерты, выпечка',
        iconSrc: '/icons/rolling-pin.png',
        subcategories: {
            pancakes: { label: 'Блины и оладьи' },
            pierogi: { label: 'Пироги и пончики' },
            cakes: { label: 'Торты' },
            rolls: { label: 'Рулеты' },
            muffins: { label: 'Кексы и маффины' },
            cheesecake: { label: 'Сырники и ватрушки' },
            'puff-pastry': { label: 'Из слоеного теста' },
            'choux-pastry': { label: 'Из заварного теста' },
            'yeast-pastry': { label: 'Из дрожжевого теста' },
            buns: { label: 'Булочки и сдоба' },
            bread: { label: 'Хлеб' },
            'pizza-dough': { label: 'Тесто на пиццу' },
            creams: { label: 'Кремы' },
        },
    },
    'grill-dish': {
        label: 'Блюда на гриле',
        iconSrc: '/icons/grill.png',
        subcategories: {
            beef: { label: 'Говядина' },
            pork: { label: 'Свинина' },
            poultry: { label: 'Птица' },
            fish: { label: 'Рыба' },
            mushrooms: { label: 'Грибы' },
            vegetables: { label: 'Овощи' },
        },
    },
    vegan: {
        label: 'Веганская кухня',
        iconSrc: '/icons/bay-leaf.png',
        subcategories: {
            snacks: { label: 'Закуски' },
            'first-dish': { label: 'Первые блюда' },
            'second-dish': { label: 'Вторые блюда' },
            garnishes: { label: 'Гарниры' },
            desserts: { label: 'Десерты' },
            pastry: { label: 'Выпечка' },
            vegan: { label: 'Сыроедческие блюда' },
            beverages: { label: 'Напитки' },
        },
    },
    'child-dish': {
        label: 'Детские блюда',
        iconSrc: '/icons/child-tasty.png',
        subcategories: {
            'first-dish': { label: 'Первые блюда' },
            'second-dish': { label: 'Вторые блюда' },
            garnish: { label: 'Гарниры' },
            pastry: { label: 'Выпечка' },
            'gluten-free': { label: 'Без глютена' },
            'sugar-free': { label: 'Без сахара' },
            'allergen-free': { label: 'Без аллергенов' },
            'food-lures': { label: 'Блюда для прикорма' },
        },
    },
    'heal-dish': {
        label: 'Лечебное питание',
        iconSrc: '/icons/pot-with-cross.svg',
        subcategories: {
            'child-food': { label: 'Детская диета' },
            'diet-1': { label: 'Диета №1' },
            'diet-2': { label: 'Диета №2' },
            'diet-4': { label: 'Диета №3' },
            'diet-5': { label: 'Диета №4' },
            'diet-6': { label: 'Диета №5' },
            'diet-7': { label: 'Диета №6' },
            'diet-8': { label: 'Диета №7' },
            'diet-9': { label: 'Диета №8' },
            'diet-10': { label: 'Диета №9' },
            'diet-11': { label: 'Диета №10' },
            'diet-12': { label: 'Диета №11' },
            'diet-13': { label: 'Диета №12' },
            'diet-14': { label: 'Диета №13' },
            'diet-15': { label: 'Диета №14' },
            'gluten-free': { label: 'Без глютена' },
            'allergen-free': { label: 'Без аллергенов' },
        },
    },
    national: {
        label: 'Национальные',
        iconSrc: '/icons/international-food.png',
        subcategories: {
            american: { label: 'Американская кухня' },
            armenian: { label: 'Армянская кухня' },
            greek: { label: 'Греческая кухня' },
            georgian: { label: 'Грузинская кухня' },
            italian: { label: 'Итальянская кухня' },
            spanish: { label: 'Испанская кухня' },
            chinese: { label: 'Китайская кухня' },
            mexican: { label: 'Мексиканская кухня' },
            'pan-asian': { label: 'Паназиатская кухня' },
            russian: { label: 'Русская кухня' },
            turkish: { label: 'Турецкая кухня' },
            french: { label: 'Французская кухня' },
            swedish: { label: 'Шведская кухня' },
            japanese: { label: 'Японская кухня' },
            other: { label: 'Другая кухня' },
        },
    },
    sauces: {
        label: 'Соусы',
        iconSrc: '/icons/mortar.png',
        subcategories: {
            meat: { label: 'Соусы мясные' },
            cheese: { label: 'Соусы сырные' },
            marinades: { label: 'Маринады' },
        },
    },
    beverages: {
        label: 'Напитки',
        iconSrc: '/icons/cup.png',
        subcategories: {
            'juices-freshes': { label: 'Соки и фреши' },
            smoothie: { label: 'Смузи' },
            kompot: { label: 'Компоты' },
            kissel: { label: 'Кисели' },
            coffee: { label: 'Кофе' },
            'heal-tea': { label: 'Лечебный чай' },
            kvas: { label: 'Квас' },
            cocktail: { label: 'Коктейли' },
            alcohol: { label: 'Алкогольные' },
        },
    },
    'ready-made': {
        label: 'Заготовки',
        iconSrc: '/icons/carrot-jar.png',
        subcategories: {
            meat: { label: 'Мясные заготовки' },
            fish: { label: 'Рыбные заготовки' },
            cucumbers: { label: 'Из огурцов' },
            tomotoes: { label: 'Из томатов' },
            mushrooms: { label: 'Из грибов' },
            vegetables: { label: 'Овощные заготовки' },
            'salads-caviar': { label: 'Салаты, икра' },
            'fruits-berries': { label: 'Из фруктов и ягод' },
        },
    },
};
