import { RecipeCategory } from './interface';

export const recipeCategoryMap: Record<string, RecipeCategory> = {
    salads: {
        index: 0,
        label: 'Салаты',
        slug: 'salads',
        iconSrc: '/icons/eggplant.png',
        description:
            'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi, non ab quia esse alias debitis ullam enim, ad possimus itaque consequuntur corrupti, mollitia numquam blanditiis quis cupiditate quas ea deleniti!',
        subcategories: {
            meat: { index: 0, label: 'Мясные салаты', slug: 'meat' },
            fish: { index: 1, label: 'Рыбные салаты', slug: 'fish' },
            vegetables: { index: 2, label: 'Овощные салаты', slug: 'vegetables' },
            'warm-salads': { index: 3, label: 'Теплые салаты', slug: 'warm-salads' },
        },
    },
    snacks: {
        index: 1,
        label: 'Закуски',
        slug: 'snacks',
        iconSrc: '/icons/healthy-eating.png',
        description:
            'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi, non ab quia esse alias debitis ullam enim, ad possimus itaque consequuntur corrupti, mollitia numquam blanditiis quis cupiditate quas ea deleniti!',
        subcategories: {
            meat: { index: 0, label: 'Мясные закуски', slug: 'meat' },
            fish: { index: 1, label: 'Рыбные закуски', slug: 'fish' },
            vegetables: { index: 2, label: 'Овощные закуски', slug: 'vegetables' },
            'warm-snacks': { index: 3, label: 'Теплые закуски', slug: 'warm-snacks' },
            sandwiches: { index: 4, label: 'Бутерброды', slug: 'sandwiches' },
            fastfood: { index: 5, label: 'Фастфуд', slug: 'fastfood' },
        },
    },
    'first-dish': {
        index: 2,
        label: 'Первые блюда',
        slug: 'first-dish',
        iconSrc: '/icons/pot.png',
        description:
            'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi, non ab quia esse alias debitis ullam enim, ad possimus itaque consequuntur corrupti, mollitia numquam blanditiis quis cupiditate quas ea deleniti!',
        subcategories: {
            fish: { index: 0, label: 'Мясные супы', slug: 'fish' },
            vegetables: { index: 1, label: 'Овощные супы', slug: 'vegetables' },
            broths: { index: 2, label: 'Бульоны', slug: 'broths' },
            cold: { index: 3, label: 'Холодные супы', slug: 'cold' },
            diet: { index: 4, label: 'Диетические супы', slug: 'diet' },
        },
    },
    'second-dish': {
        index: 3,
        label: 'Вторые блюда',
        slug: 'second-dish',
        iconSrc: '/icons/frying-pan.png',
        description:
            'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi, non ab quia esse alias debitis ullam enim, ad possimus itaque consequuntur corrupti, mollitia numquam blanditiis quis cupiditate quas ea deleniti!',
        subcategories: {
            meat: { index: 0, label: 'Мясные', slug: 'meat' },
            fish: { index: 1, label: 'Рыбные', slug: 'fish' },
            vegetables: { index: 2, label: 'Овощные', slug: 'vegetables' },
            'poultry-dish': { index: 3, label: 'Из птицы', slug: 'poultry-dish' },
            'mushroom-dish': { index: 4, label: 'Из грибов', slug: 'mushroom-dish' },
            'byproduct-dish': { index: 5, label: 'Из субпродуктов', slug: 'byproduct-dish' },
            'steamed-dish': { index: 6, label: 'На пару', slug: 'steamed-dish' },
            pierogi: { index: 7, label: 'Пельмени, вареники', slug: 'pierogi' },
            'flour-garnish': { index: 8, label: 'Мучные гарниры', slug: 'flour-garnish' },
            'vegetebles-garnish': {
                index: 9,
                label: 'Овощные гарниры',
                slug: 'vegetebles-garnish',
            },
            pizza: { index: 10, label: 'Пицца', slug: 'pizza' },
            sushi: { index: 11, label: 'Суши', slug: 'sushi' },
        },
    },
    'desserts-pastry': {
        index: 4,
        label: 'Десерты, выпечка',
        slug: 'desserts-pastry',
        iconSrc: '/icons/rolling-pin.png',
        description:
            'Без них невозможно представить себе ни современную, ни традиционную кулинарию. Пироги и печенья, блины, пончики, вареники и, конечно, хлеб - рецепты изделий из теста многообразны и невероятно популярны.',
        subcategories: {
            pancakes: { index: 0, label: 'Блины и оладьи', slug: 'pancakes' },
            pierogi: { index: 1, label: 'Пироги и пончики', slug: 'pierogi' },
            cakes: { index: 2, label: 'Торты', slug: 'cakes' },
            rolls: { index: 3, label: 'Рулеты', slug: 'rolls' },
            muffins: { index: 4, label: 'Кексы и маффины', slug: 'muffins' },
            cheesecake: { index: 5, label: 'Сырники и ватрушки', slug: 'cheesecake' },
            'puff-pastry': { index: 6, label: 'Из слоеного теста', slug: 'puff-pastry' },
            'choux-pastry': { index: 7, label: 'Из заварного теста', slug: 'choux-pastry' },
            'yeast-pastry': { index: 8, label: 'Из дрожжевого теста', slug: 'yeast-pastry' },
            buns: { index: 9, label: 'Булочки и сдоба', slug: 'buns' },
            bread: { index: 10, label: 'Хлеб', slug: 'bread' },
            'pizza-dough': { index: 11, label: 'Тесто на пиццу', slug: 'pizza-dough' },
            creams: { index: 12, label: 'Кремы', slug: 'creams' },
        },
    },
    'grill-dish': {
        index: 5,
        label: 'Блюда на гриле',
        slug: 'grill-dish',
        iconSrc: '/icons/grill.png',
        description:
            'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi, non ab quia esse alias debitis ullam enim, ad possimus itaque consequuntur corrupti, mollitia numquam blanditiis quis cupiditate quas ea deleniti!',
        subcategories: {
            beef: { index: 0, label: 'Говядина', slug: 'beef' },
            pork: { index: 1, label: 'Свинина', slug: 'pork' },
            poultry: { index: 2, label: 'Птица', slug: 'poultry' },
            fish: { index: 3, label: 'Рыба', slug: 'fish' },
            mushrooms: { index: 4, label: 'Грибы', slug: 'mushrooms' },
            vegetables: { index: 5, label: 'Овощи', slug: 'vegetables' },
        },
    },
    vegan: {
        index: 6,
        label: 'Веганская кухня',
        slug: 'vegan',
        iconSrc: '/icons/bay-leaf.png',
        description:
            'Интересны не только убеждённым вегетарианцам, но и тем, кто хочет попробовать вегетарианскую диету и готовить вкусные вегетарианские блюда.',
        subcategories: {
            snacks: { index: 0, label: 'Закуски', slug: 'snacks' },
            'first-dish': { index: 1, label: 'Первые блюда', slug: 'first-dish' },
            'second-dish': { index: 2, label: 'Вторые блюда', slug: 'second-dish' },
            garnishes: { index: 3, label: 'Гарниры', slug: 'garnishes' },
            desserts: { index: 4, label: 'Десерты', slug: 'desserts' },
            pastry: { index: 5, label: 'Выпечка', slug: 'pastry' },
            vegan: { index: 6, label: 'Сыроедческие блюда', slug: 'vegan' },
            beverages: { index: 7, label: 'Напитки', slug: 'beverages' },
        },
    },
    'child-dish': {
        index: 7,
        label: 'Детские блюда',
        slug: 'child-dish',
        iconSrc: '/icons/child-tasty.png',
        description:
            'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi, non ab quia esse alias debitis ullam enim, ad possimus itaque consequuntur corrupti, mollitia numquam blanditiis quis cupiditate quas ea deleniti!',
        subcategories: {
            'first-dish': { index: 0, label: 'Первые блюда', slug: 'first-dish' },
            'second-dish': { index: 1, label: 'Вторые блюда', slug: 'second-dish' },
            garnish: { index: 2, label: 'Гарниры', slug: 'garnish' },
            pastry: { index: 3, label: 'Выпечка', slug: 'pastry' },
            'gluten-free': { index: 4, label: 'Без глютена', slug: 'gluten-free' },
            'sugar-free': { index: 5, label: 'Без сахара', slug: 'sugar-free' },
            'allergen-free': { index: 6, label: 'Без аллергенов', slug: 'allergen-free' },
            'food-lures': { index: 7, label: 'Блюда для прикорма', slug: 'food-lures' },
        },
    },
    'heal-dish': {
        index: 8,
        label: 'Лечебное питание',
        slug: 'heal-dish',
        iconSrc: '/icons/pot-with-cross.svg',
        description:
            'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi, non ab quia esse alias debitis ullam enim, ad possimus itaque consequuntur corrupti, mollitia numquam blanditiis quis cupiditate quas ea deleniti!',
        subcategories: {
            'child-food': { index: 0, label: 'Детская диета', slug: 'child-food' },
            'diet-1': { index: 1, label: 'Диета №1', slug: 'diet-1' },
            'diet-2': { index: 2, label: 'Диета №2', slug: 'diet-2' },
            'diet-4': { index: 3, label: 'Диета №3', slug: 'diet-4' },
            'diet-5': { index: 4, label: 'Диета №4', slug: 'diet-5' },
            'diet-6': { index: 5, label: 'Диета №5', slug: 'diet-6' },
            'diet-7': { index: 6, label: 'Диета №6', slug: 'diet-7' },
            'diet-8': { index: 7, label: 'Диета №7', slug: 'diet-8' },
            'diet-9': { index: 8, label: 'Диета №8', slug: 'diet-9' },
            'diet-10': { index: 9, label: 'Диета №9', slug: 'diet-10' },
            'diet-11': { index: 10, label: 'Диета №10', slug: 'diet-11' },
            'diet-12': { index: 11, label: 'Диета №11', slug: 'diet-12' },
            'diet-13': { index: 12, label: 'Диета №12', slug: 'diet-13' },
            'diet-14': { index: 13, label: 'Диета №13', slug: 'diet-14' },
            'diet-15': { index: 14, label: 'Диета №14', slug: 'diet-15' },
            'gluten-free': { index: 15, label: 'Без глютена', slug: 'gluten-free' },
            'allergen-free': { index: 16, label: 'Без аллергенов', slug: 'allergen-free' },
        },
    },
    national: {
        index: 9,
        label: 'Национальные',
        slug: 'national',
        iconSrc: '/icons/international-food.png',
        description:
            'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi, non ab quia esse alias debitis ullam enim, ad possimus itaque consequuntur corrupti, mollitia numquam blanditiis quis cupiditate quas ea deleniti!',
        subcategories: {
            american: { index: 0, label: 'Американская кухня', slug: 'american' },
            armenian: { index: 1, label: 'Армянская кухня', slug: 'armenian' },
            greek: { index: 2, label: 'Греческая кухня', slug: 'greek' },
            georgian: { index: 3, label: 'Грузинская кухня', slug: 'georgian' },
            italian: { index: 4, label: 'Итальянская кухня', slug: 'italian' },
            spanish: { index: 5, label: 'Испанская кухня', slug: 'spanish' },
            chinese: { index: 6, label: 'Китайская кухня', slug: 'chinese' },
            mexican: { index: 7, label: 'Мексиканская кухня', slug: 'mexican' },
            'pan-asian': { index: 8, label: 'Паназиатская кухня', slug: 'pan-asian' },
            russian: { index: 9, label: 'Русская кухня', slug: 'russian' },
            turkish: { index: 10, label: 'Турецкая кухня', slug: 'turkish' },
            french: { index: 11, label: 'Французская кухня', slug: 'french' },
            swedish: { index: 12, label: 'Шведская кухня', slug: 'swedish' },
            japanese: { index: 13, label: 'Японская кухня', slug: 'japanese' },
            other: { index: 14, label: 'Другая кухня', slug: 'other' },
        },
    },
    sauces: {
        index: 10,
        label: 'Соусы',
        slug: 'sauces',
        iconSrc: '/icons/mortar.png',
        description:
            'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi, non ab quia esse alias debitis ullam enim, ad possimus itaque consequuntur corrupti, mollitia numquam blanditiis quis cupiditate quas ea deleniti!',
        subcategories: {
            meat: { index: 0, label: 'Соусы мясные', slug: 'meat' },
            cheese: { index: 1, label: 'Соусы сырные', slug: 'cheese' },
            marinades: { index: 2, label: 'Маринады', slug: 'marinades' },
        },
    },
    beverages: {
        index: 11,
        label: 'Напитки',
        slug: 'beverages',
        iconSrc: '/icons/cup.png',
        description:
            'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi, non ab quia esse alias debitis ullam enim, ad possimus itaque consequuntur corrupti, mollitia numquam blanditiis quis cupiditate quas ea deleniti!',
        subcategories: {
            'juices-freshes': { index: 0, label: 'Соки и фреши', slug: 'juices-freshes' },
            smoothie: { index: 1, label: 'Смузи', slug: 'smoothie' },
            kompot: { index: 2, label: 'Компоты', slug: 'kompot' },
            kissel: { index: 3, label: 'Кисели', slug: 'kissel' },
            coffee: { index: 4, label: 'Кофе', slug: 'coffee' },
            'heal-tea': { index: 5, label: 'Лечебный чай', slug: 'heal-tea' },
            kvas: { index: 6, label: 'Квас', slug: 'kvas' },
            cocktail: { index: 7, label: 'Коктейли', slug: 'cocktail' },
            alcohol: { index: 8, label: 'Алкогольные', slug: 'alcohol' },
        },
    },
    'ready-made': {
        index: 12,
        label: 'Заготовки',
        slug: 'ready-made',
        iconSrc: '/icons/carrot-jar.png',
        description:
            'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi, non ab quia esse alias debitis ullam enim, ad possimus itaque consequuntur corrupti, mollitia numquam blanditiis quis cupiditate quas ea deleniti!',
        subcategories: {
            meat: { index: 0, label: 'Мясные заготовки', slug: 'meat' },
            fish: { index: 1, label: 'Рыбные заготовки', slug: 'fish' },
            cucumbers: { index: 2, label: 'Из огурцов', slug: 'cucumbers' },
            tomotoes: { index: 3, label: 'Из томатов', slug: 'tomotoes' },
            mushrooms: { index: 4, label: 'Из грибов', slug: 'mushrooms' },
            vegetables: { index: 5, label: 'Овощные заготовки', slug: 'vegetables' },
            'salads-caviar': { index: 6, label: 'Салаты, икра', slug: 'salads-caviar' },
            'fruits-berries': { index: 7, label: 'Из фруктов и ягод', slug: 'fruits-berries' },
        },
    },
};
